import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <h1 className='text-3xl font-bold underline text-teal-400'>
          Welcome to <a href='#'>Next.js!</a>
        </h1>
        <Link href='landing'>
          <a>landing page</a>
        </Link>
      </main>

      <footer>Footer</footer>
    </div>
  );
}
